
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#debugpy:
wake_on_lan:

#logger:
#  default: info
#  logs:
#    custom_components.mega: debug

yandex_station_intents: # https://github.com/dext0r/ha-yandex-station-intents
  intents:
    Включи телевизор:
      extra_phrases:                  
        - Телевизор
      say_phrase: Слушаюсь, хозяин
    Выключи телевизор: Окей
    Включи окко: Окей, включаю окко
    Включи кинопоиск: Окей, включаю кинопоиск
    Включи тюбик:  Окей, включаю ютюб 
    

mega:  #https://andvikt.github.io/mega_hacs/
  mega2:
    #filter_scale: 5
    led:
      some_led2:
        ws28xx: true
        port: 35
        order: brg
        smooth: 100
  
automation water:
  - alias: automation cold water
    trigger:
      - entity_id: binary_sensor.mega2_20
        platform: state
        from: 'on'
        to: 'off'
    action:
        - data:
            entity_id:
              - counter.cold_water_counter
          service: counter.increment
          
  - alias: automation hot water
    trigger:
      - entity_id: binary_sensor.mega2_21
        platform: state
        from: 'on'
        to: 'off'
    action:
        - data:
            entity_id:
              - counter.hot_water_counter
          service: counter.increment
                 
automation dd1:               
  - alias: Датчик движения 1э выключить свет прихожая
    trigger:
      platform: state
      entity_id: binary_sensor.mega1_28
      to: 'on'
      for: '00:05:00'
    action:
      service: light.turn_off
      entity_id: light.mega1_00
      
  - alias: Датчик движения 1э выключить свет туалет
    trigger:
      platform: state
      entity_id: binary_sensor.mega1_28
      to: 'on'
      for: '00:15:00'
    action:
      service: light.turn_off
      entity_id: light.mega1_08
      
automation dd2:        
  - alias: Датчик движения 2э включить
    trigger:
      platform: state
      entity_id: binary_sensor.mega2_15
      to: 'off'
    condition: 
       - condition: state
         entity_id: sun.sun
         state: below_horizon
       - condition: state
         entity_id: light.mega2_13 #лестница 
         state: 'off'
       - condition: state
         entity_id: light.mega2_07 #кабинет         
         state: 'off'
       - condition: state
         entity_id: light.mega2_11 #спальня
         state: 'off'         
       - condition: state
         entity_id: light.mega2_08 #детская
         state: 'off'
         
    action:
      service: light.turn_on
      entity_id: light.mega2_12
      data:
        brightness: 60
        
  - alias: Датчик движения 2э выключить
    trigger:
      platform: state
      entity_id: binary_sensor.mega2_15
      to: 'on'
      for: '00:00:05'
    condition:
      condition: numeric_state
      entity_id: light.mega2_12
      attribute: brightness
      below: 255
    action:
      service: light.turn_off
      entity_id: light.mega2_12
      
  - alias: Датчик движения 2э выключить свет лестница
    trigger:
      platform: state
      entity_id: binary_sensor.mega2_15
      to: 'on'
      for: '00:05:00'
    action:
      service: light.turn_off      
      target:
        entity_id:
          - light.mega2_12
          - light.mega2_13          
      
  - alias: Датчик движения 2э выключить свет туалет
    trigger:
      platform: state
      entity_id: binary_sensor.mega2_15
      to: 'on'
      for: '00:15:00'
    action:
      service: light.turn_off
      entity_id: light.mega2_10
      
  - alias: Датчик движения 2э выключить свет ванна
    trigger:
      platform: state
      entity_id: binary_sensor.mega2_15
      to: 'on'
      for: '00:20:00'
    action:
      service: light.turn_off
      entity_id: light.mega2_25
              
automation vent:        
  - alias: вентилятор в туалете 2э
    trigger:
      platform: state
      entity_id: light.mega2_10 # свет в туалете 2э
      to: 'on'
      for: '00:02:00'
    action:
      service: light.turn_on
      entity_id: light.mega2_28 # вент в туалете 2э
      
  - alias: вентилятор в туалете 2э выключить
    trigger:
      platform: state
      entity_id: light.mega2_28
      to: 'on'
      for: '00:10:00'
    action:
      service: light.turn_off
      entity_id: light.mega2_28


  - alias: вентилятор в туалете 1э
    trigger:
      platform: state
      entity_id: light.mega1_08 # свет в туалете 1э
      to: 'on'
      for: '00:02:00'
    action:
      service: light.turn_on
      entity_id: light.mega1_02 # вент в туалете 1э
      
  - alias: вентилятор в туалете 1э выключить
    trigger:
      platform: state
      entity_id: light.mega1_02
      to: 'on'
      for: '00:10:00'
    action:
      service: light.turn_off
      entity_id: light.mega1_02

  - alias: рекупы включить
    trigger:
      platform: time      
      at: "21:00:00"
    condition: 
       condition: state
       entity_id: device_tracker.m2103k19pg_2 # Poco phone
       state: home
    action:
      service: light.turn_on
      entity_id: light.mega2_26

  - alias: рекупы выключить
    trigger:
      platform: time      
      at: "09:00:00"    
    action:
      service: light.turn_off
      entity_id: light.mega2_26
      
#sensor:
  #- platform: template
   # sensors:
    #  cold_water_sensor:
     #   friendly_name: "Показания"
     
     
    
automation tv:    
  - alias: Кнопка включить ТВ
    trigger:   
      - platform: webostv.turn_on
        entity_id: media_player.lg_webos_tv_sm8600pla
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: 20:17:42:DC:D7:56
          
  - alias: Alisa выключи телевизор
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Выключи телевизор          
    action:
      - service: media_player.turn_off
        entity_id:  media_player.lg_webos_tv_sm8600pla
  
  - alias: Включить кинопоиск
    use_blueprint:
      path: vkp/tv.yaml
      input:
        alisa_phrase: Включи кинопоиск
        tv_source: Кинопоиск
  
  - alias: Включить окко
    use_blueprint:
      path: vkp/tv.yaml
      input:
        alisa_phrase: Включи окко
        tv_source: Okko фильмы и сериалы HD
  
  - alias: Включить телик
    use_blueprint:
      path: vkp/tv.yaml
      input:
        alisa_phrase: Включи телевизор
        tv_source: TVIP Media
  
  - alias: Включить тюб
    use_blueprint:
      path: vkp/tv.yaml
      input:
        alisa_phrase: Включи тюбик
        tv_source: YouTube
        
script my:
  test_script:
    sequence:
      - service: media_player.turn_off
        entity_id: media_player.yandex_station_ff98f02980eeffdc6b865953
        
automation click:
  - alias: туалет 2э
    trigger:
      platform: state
      entity_id: light.mega2_10
      to: 'on'
    condition:      
      - condition: time      
        after: "22:30:00"
        before: "07:00:00"
    action:
      service: light.turn_on
      entity_id: light.mega2_10
      data:
        brightness: 55
        
  - alias: stair
    trigger:
    - platform: event
      event_type: mega.binary
      event_data:
        entity_id: binary_sensor.mega1_24
        type: single
    action:
      - service: light.toggle
        entity_id: light.mega2_13 
    
  - alias: hallway
    trigger:
    - platform: event
      event_type: mega.binary
      event_data:
        entity_id: binary_sensor.mega1_25
        type: long
    action:      
      - service: light.turn_off
        entity_id: light.floor2
        
      - service: media_player.turn_off
        entity_id: media_player.yandex_station_ff98f02980eeffdc6b865953
    

sensor:
  - platform: template
    sensors:
      cold_water_sensor:
        friendly_name: "Холодная вода, м3"
        unit_of_measurement: 'М3'
        value_template: "{{ (states('counter.cold_water_counter') | float) / 100 }}"
        icon_template: mdi:water-outline
        
  - platform: template
    sensors:      
      hot_water_sensor:
        friendly_name: "Горячая вода, м3"
        unit_of_measurement: 'М3'
        value_template: "{{ (states('counter.hot_water_counter') | float) / 100 }}"
        icon_template: mdi:water-thermometer-outline
        
utility_meter:
  cold_water_daily:
    name: "Холодная вода в день"
    source: sensor.cold_water_sensor
    cycle: daily
  hot_water_daily:
    name: "Горячая вода в день"
    source: sensor.hot_water_sensor
    cycle: daily